# Generated by Django 2.1 on 2019-04-19 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('website', models.URLField(blank=True, max_length=300)),
                ('biography', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='users/pictures')),
                ('followers', models.ManyToManyField(related_name='following', to='users.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-updated'],
                'abstract': False,
            },
        ),
    ]
